Completed rough general layout
luke-grayland/luke-grayland.github.io pull request #1
Opened 2022-01-17 14:13 UTC by luke-grayland

I've completed the general layout (nav bar, header, about me, projects, footer) and will be adding content and further detail next. The lorem ipsum text can be ignored for now. Thanks!

2022-01-17 15:08 UTC, j-add requested changes
Looking good, just needs some small changes and content adding to footer

2022-01-17 15:08 UTC, j-add commented on portfolioMain.html
> +<html>
Could do with a `lang` attribute

2022-01-17 15:11 UTC, luke-grayland commented on portfolioMain.html
> +<head>
Good point, have added one

2022-01-17 15:12 UTC, luke-grayland commented on portfolioMain.html
> +		<p>I am a footer </p>
Yes, I'll add some content now

2022-01-17 15:12 UTC, luke-grayland commented on portfolioStyle.css
> +	color: var(--greyBlue);
Good shout - I'll change it from switching to the lighter colour

2022-01-17 15:16 UTC, luke-grayland commented on portfolioStyle.css
> +	margin: auto auto;
Ah cool, I didn't know that

2022-01-19 13:55 UTC, gabrielrowan reviewed
I could only find 1 thing! A double semi colon - but not sure if this is intentional for that particular style type

2022-01-19 13:58 UTC, merged